//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_Contact> tbl_Contact { get; set; }
        public DbSet<tbl_Customer> tbl_Customer { get; set; }
        public DbSet<tbl_Manager> tbl_Manager { get; set; }
        public DbSet<tbl_Meeting> tbl_Meeting { get; set; }
        public DbSet<tbl_MeetingGoal> tbl_MeetingGoal { get; set; }
        public DbSet<tbl_MeetingResult> tbl_MeetingResult { get; set; }
        public DbSet<tbl_Task> tbl_Task { get; set; }
        public DbSet<tbl_TaskResult> tbl_TaskResult { get; set; }
        public DbSet<tbl_TaskType> tbl_TaskType { get; set; }
    }
}
