//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public tbl_Contact()
        {
            this.tbl_Customer = new HashSet<tbl_Customer>();
            this.tbl_Manager = new HashSet<tbl_Manager>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Telephone { get; set; }
        public string E_mail { get; set; }
    
        public virtual ICollection<tbl_Customer> tbl_Customer { get; set; }
        public virtual ICollection<tbl_Manager> tbl_Manager { get; set; }
    }
}
