//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Meeting
    {
        public System.Guid ID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid ManagerID { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid GoalID { get; set; }
        public System.Guid ResultID { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Manager tbl_Manager { get; set; }
        public virtual tbl_MeetingGoal tbl_MeetingGoal { get; set; }
        public virtual tbl_MeetingResult tbl_MeetingResult { get; set; }
    }
}
